use crate::config::Config;
use anyhow::{Context, Result};
use lettre::message::{Attachment, Mailbox, MultiPart, SinglePart, header::ContentType};
use lettre::transport::smtp::authentication::Credentials;
use lettre::{Message, SmtpTransport, Transport};
use std::fs;
use std::path::Path;

pub fn send_epub(config: &Config, title: &str, source: &str, epub_path: &Path) -> Result<()> {
    let epub_bytes = fs::read(epub_path)
        .with_context(|| format!("failed to read EPUB {}", epub_path.display()))?;
    let filename = epub_path
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or("thread.epub")
        .to_string();
    let epub_type = ContentType::parse("application/epub+zip")?;
    let email = Message::builder()
        .from(config.from_email.parse::<Mailbox>()?)
        .to(config.kindle_email.parse::<Mailbox>()?)
        .subject(title)
        .multipart(
            MultiPart::mixed()
                .singlepart(SinglePart::plain(format!(
                    "Generated by kindlecast from {source}."
                )))
                .singlepart(Attachment::new(filename).body(epub_bytes, epub_type)),
        )
        .context("failed to build email message")?;

    let creds = Credentials::new(config.smtp_username.clone(), config.smtp_password.clone());
    let mailer = SmtpTransport::relay(&config.smtp_host)
        .with_context(|| format!("failed to configure SMTP relay {}", config.smtp_host))?
        .credentials(creds)
        .build();
    mailer
        .send(&email)
        .context("SMTP send failed; check app password and approved sender list")?;
    Ok(())
}
